### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Hqss** [skyhehe123/SA-SSD#1]
Please tell me the address of the paper. Thank you.

**Comment by York1996OutLook** [comment]
+1

**Comment by cherryjm** [comment]
+1

**Comment by stduent-vehicle** [comment]
https://www4.comp.polyu.edu.hk/~cslzhang/paper/SA-SSD.pdf

**Comment by wangguojun2018** [comment]
> https://www4.comp.polyu.edu.hk/~cslzhang/paper/SA-SSD.pdf

这个链接打不开，好像没有访问权限

**Comment by stduent-vehicle** [comment]
我今天试了下，论文链接可以打开，你再试试吧。



---Original---

**Comment by wangguojun2018** [comment]
嗯嗯，好的，谢谢啦


 
---Original---
