### ISSUE TITLE
No package named  "mmdet/tools"

### ISSUE THREAD

**Issue by dongqiaqia** [skyhehe123/SA-SSD#2]
I think that there are some mistake in your readme: "cd mmdet/toos".

**Comment by Morgan-Gan** [comment]
Yes, I think so! The "cd mmdet/tools"  maybe mean the upfolders-tools

**Comment by abhigoku10** [comment]
@dongqiaqia @Morgan-Gan @skyhehe123  any one able to solve this error ???
