### ISSUE TITLE
Very long trining time

### ISSUE THREAD

**Issue by asadnorouzi** [skyhehe123/SA-SSD#21]
@skyhehe123 Thank you for sharing your awesome work :)

I was wondering if it is normal for training to take VERY long time. I am training with 8 GPUs and it only saved the first checkpoint (epoch 5) after 5 hours.

By the way, I'm testing your pipeline with pseudo lidar dataset. Any thoughts?

**Comment by stalkermustang** [comment]
It's strange, because im training with  4 GPUs 100 epochs (960 samples per epoch) with increased pointcloud ranges in 12 hours , unsing BS 6 per GPU. Can you debug or profile code to define part that take much time? What's CPU you use - there's some numba-ops in data preprocessing, and one or two cores can cause issues.

**Comment by asadnorouzi** [comment]
@stalkermustang  I have 96 CPUs! All 8 GPUs are fully utilized, almost at 100%. It's also very strange to me why training is taking a long time. It's been almost 12 hours and only 10 epochs have lapsed.  I had to make some changes to get dist_train.sh script to work with multiple GPUs. In the output there are many user warnings from `numba`  and `pytorch` which are mainly due to old vs new versions. I am using `pytorch 1.4`, `CUDA 10.1`, and `numba 0.48`. I am running it in docker. I had shared memory error which crashed the train script. I had to run docker with increased shared memory which solved the crash.
Any idea?

**Comment by abhigoku10** [comment]
@asadnorouzi  hi are you able to perform the training ?? i am nto able to setup the repo there is difference in both readme and code setup  i am getting a below error "from mmdet.ops.points_op import points_op_cpu
ImportError:/march23/SA-SSD/mmdet/ops/points_op/points_op_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv"

**Comment by abhigoku10** [comment]
@stalkermustang @asadnorouzi  where you able to set up the environment can you share the env which you have used it , i am using 2080Ti . I get error at the spconv or in cudnn

**Comment by asadnorouzi** [comment]
@abhigoku10 You can see my env in the comment above. You need to make sure that you install `spconv==1.0`. The `spconv` repo has been updated to v1.1 as default. I don't have error, but my issue is the long training time which is not normal.

**Comment by abhigoku10** [comment]
@asadnorouzi thanks for the response
