### ISSUE TITLE
result problem

### ISSUE THREAD

**Issue by MichaelSunEngineer** [skyhehe123/SA-SSD#30]
@skyhehe123 Hi, I want to use your-greate-job(SA-SSD) to detect the point cloud, which is the data in KITTI data set. But when I use one of the point cloud data to execute test.py, I am confused about the format of the result output. In addition, how can I link the lidar to directly obtain the point cloud for detection? And what should I do for the visualization of the detection results on the point cloud and pictures? thank you.
this is print of result,all score is 0.5??
`len(box2d) ==  125
len(box3d) ==  125
len(labels) ==  125
len(scores) ==  125
len(alphas) ==  125
anno['name'] ==  ['Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car']
anno['alpha'] ==  [-0.8114124, -0.76817256, 0.87327915, 0.95776707, 0.9456352, -0.32573646, -0.25792053, -0.30250496, -0.240692, -0.78396195, 0.9334787, 1.0212665, -0.8473692, 1.350681, 1.411958, 1.0146813, -0.852052, 0.9348588, 1.1050543, -0.8578755, 1.0480633, 0.9329846, 1.1439047, -0.8430864, -0.58747715, 1.1419666, 1.2202781, -0.90456665, 0.9696237, -0.53870666, 1.2294647, 1.3038844, 0.9754964, -0.40851188, -0.16923535, -1.0020602, -0.50542945, 1.3049918, 1.3718741, -0.1454561, 0.9536649, -0.3621726, -0.3751409, -0.47301173, 1.3769011, 1.520198, 0.71565586, 1.4378908, 1.4937253, 1.1436299, -0.34584963, 1.5455817, 1.4264474, -0.23942009, 1.4863386, 1.5076964, 1.3653245, -0.0496391, 1.3804783, 1.5376308, 1.5616179, 1.5417559, -0.05360566, -0.03345954, -0.04262371, 1.6465737, 1.6339244, 1.6280268, -0.016863842, 1.6314856, 1.7391808, 0.03363016, 1.7328085, 1.6865547, 2.0045292, 1.851491, 0.098852135, 1.8120807, 2.1107776, 1.77022, 0.10920398, 1.9339721, 1.8762975, 2.1733708, 1.8528128, 1.9963326, 2.468287, 2.2143302, 1.9871589, 1.9442859, 0.26573336, 2.1576767, 2.4562926, 2.1203418, 2.3439326, 2.0528193, 2.0054052, 2.270378, 2.1711392, 2.102034, 2.4177585, 2.2938738, 2.1262894, 0.6103638, 2.3986473, 0.6073715, 2.1906655, 0.43831033, 0.7496975, 2.260682, 0.563818, 0.44466037, 0.54249865, 0.51094836, 2.3609002, 2.2968833, 2.234919, 0.5421421, 0.54340327, 2.3384347, 2.2669163, 2.1968474, 2.3424256, 2.2744663]
anno['dimensions'] ==  [array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.8507767, 1.5223237, 1.5674287], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32), array([3.9312568, 1.6605717, 1.6659559], dtype=float32)]
anno['location'] ==  [array([17.925062 ,  1.4332855, 17.403692 ], dtype=float32), array([17.922508 ,  1.4248525, 19.00367  ], dtype=float32), array([15.829199 ,  1.5180372, 16.816782 ], dtype=float32), array([15.824091 ,  1.5011712, 20.016733 ], dtype=float32), array([14.627383,  1.527131, 18.014929], dtype=float32), array([14.28131  ,  1.3340709, 44.997772 ], dtype=float32), array([14.259603 ,  1.2623903, 58.597565 ], dtype=float32), array([13.479462 ,  1.3380251, 46.196533 ], dtype=float32), array([13.457755 ,  1.2663444, 59.796326 ], dtype=float32), array([13.131846 ,  1.5160419, 13.396419 ], dtype=float32), array([13.031347 ,  1.5603384, 15.612519 ], dtype=float32), array([13.02624  ,  1.5434723, 18.812473 ], dtype=float32), array([12.735072 ,  1.5317225, 11.395837 ], dtype=float32), array([12.186086,  1.420931, 44.010864], dtype=float32), array([12.164379 ,  1.3492502, 57.61066  ], dtype=float32), array([11.829534,  1.569432, 16.810669], dtype=float32), array([11.537089 ,  1.5534658, 10.194022 ], dtype=float32), array([11.035346 ,  1.5986854, 13.209499 ], dtype=float32), array([11.025769 ,  1.5670614, 19.20941  ], dtype=float32), array([10.339105,  1.575209,  8.992206], dtype=float32), array([10.231583 ,  1.5963148, 15.60824  ], dtype=float32), array([ 9.438673 ,  1.6297846, 11.207084 ], dtype=float32), array([ 9.42782  ,  1.5939441, 18.00698  ], dtype=float32), array([8.741153 , 1.6020917, 7.7897787], dtype=float32), array([ 8.732215,  1.572576, 13.389694], dtype=float32), array([ 8.2317505,  1.6220121, 15.605184 ], dtype=float32), array([ 8.226005 ,  1.6030378, 19.20513  ], dtype=float32), array([7.9437747, 1.6208037, 6.18858  ], dtype=float32), array([ 7.8407226,  1.6566672, 10.004658 ], dtype=float32), array([ 7.134266 ,  1.5994588, 12.187267 ], dtype=float32), array([ 7.029937 ,  1.6311058, 16.803333 ], dtype=float32), array([ 6.6248612,  1.6193792, 20.002672 ], dtype=float32), array([6.244046 , 1.6877664, 8.002242 ], dtype=float32), array([ 5.9311733,  1.6043359, 14.185403 ], dtype=float32), array([ 5.89159  ,  1.4736239, 38.985027 ], dtype=float32), array([5.5484433, 1.6663984, 3.3849552], dtype=float32), array([ 5.5375896,  1.630558 , 10.184853 ], dtype=float32), array([ 5.430707,  1.653772, 16.400892], dtype=float32), array([ 5.0256352,  1.6420454, 19.600233 ], dtype=float32), array([ 5.0897427,  1.477578 , 40.18379  ], dtype=float32), array([4.6480126, 1.7209738, 5.5998335], dtype=float32), array([ 4.7331886,  1.6260791, 12.983586 ], dtype=float32), array([ 4.3357744,  1.6396517, 11.382999 ], dtype=float32), array([3.941556 , 1.6637654, 7.782443 ], dtype=float32), array([ 3.8327577,  1.6806546, 15.198465 ], dtype=float32), array([ 3.7963667,  1.5604839, 37.998116 ], dtype=float32), array([3.4532197, 1.7532583, 2.3980486], dtype=float32), array([ 3.4276822,  1.668928 , 18.397806 ], dtype=float32), array([ 3.414275 ,  1.6246547, 26.79768  ], dtype=float32), array([3.048148 , 1.7415317, 5.5973883], dtype=float32), array([3.1397083, 1.6677196, 8.981202 ], dtype=float32), array([ 2.9926038,  1.5581133, 40.39686  ], dtype=float32), array([ 2.6360497,  1.7066144, 13.196661 ], dtype=float32), array([ 2.337857 ,  1.6716738, 10.179962 ], dtype=float32), array([ 2.2309742,  1.6948878, 16.396002 ], dtype=float32), array([ 2.2258666,  1.6780218, 19.595955 ], dtype=float32), array([1.8463324, 1.7506255, 6.7955365], dtype=float32), array([ 1.4740808,  1.4711269, 50.178135 ], dtype=float32), array([1.0508693, 1.7756622, 3.9943564], dtype=float32), array([ 1.037462 ,  1.7313888, 12.394229 ], dtype=float32), array([ 1.0291623,  1.7039814, 17.59415  ], dtype=float32), array([0.6445169, 1.7597191, 7.9936843], dtype=float32), array([ 0.72011626,  1.6332005 , 21.377346  ], dtype=float32), array([ 0.6722332,  1.4750811, 51.376892 ], dtype=float32), array([ 0.33100167,  1.6741804 , 14.576838  ], dtype=float32), array([-0.15094632,  1.7847558 ,  5.1925044 ], dtype=float32), array([-0.15924604,  1.7573485 , 10.392426  ], dtype=float32), array([-0.17265327,  1.713075  , 18.7923    ], dtype=float32), array([-0.08173131,  1.6371547 , 22.576105  ], dtype=float32), array([-0.6211427,  1.557987 , 49.191223 ], dtype=float32), array([-0.9547092,  1.7823852,  7.591245 ], dtype=float32), array([-0.8708101,  1.683274 , 15.774985 ], dtype=float32), array([-1.3610616,  1.7664422, 11.590573 ], dtype=float32), array([-1.3744688,  1.7221688, 19.990446 ], dtype=float32), array([-1.7488992,  1.8116386,  3.9900773], dtype=float32), array([-2.1565247,  1.791479 ,  8.789393 ], dtype=float32), array([-2.0726256,  1.6923677, 16.973135 ], dtype=float32), array([-2.5628772,  1.7755358, 12.788721 ], dtype=float32), array([-2.950711 ,  1.8207322,  5.1882253], dtype=float32), array([-2.9730563,  1.7469431, 19.188013 ], dtype=float32), array([-2.8802192,  1.6773475, 21.771837 ], dtype=float32), array([-3.3583403,  1.8005726,  9.987541 ], dtype=float32), array([-3.7646928,  1.7846296, 13.986869 ], dtype=float32), array([-4.1525264,  1.8298259,  6.386373 ], dtype=float32), array([-4.1697645,  1.7729028, 17.18621  ], dtype=float32), array([-4.560156 ,  1.8096663, 11.185688 ], dtype=float32), array([-5.3492346,  1.8557856,  4.3845696], dtype=float32), array([-5.354342 ,  1.8389195,  7.584521 ], dtype=float32), array([-5.363919 ,  1.8072957, 13.58443  ], dtype=float32), array([-5.7689943,  1.7955691, 16.783772 ], dtype=float32), array([-5.6755185,  1.7280817, 18.967602 ], dtype=float32), array([-6.158105 ,  1.8365489,  9.983261 ], dtype=float32), array([-6.55105  ,  1.8648793,  5.582717 ], dtype=float32), array([-6.961868 ,  1.8341783, 12.382003 ], dtype=float32), array([-7.354813 ,  1.8625087,  7.981458 ], dtype=float32), array([-7.3669434,  1.8224518, 15.581343 ], dtype=float32), array([-7.772019 ,  1.8107252, 18.780685 ], dtype=float32), array([-8.158576,  1.860138, 10.380199], dtype=float32), array([-8.563651 ,  1.8484116, 13.579539 ], dtype=float32), array([-8.968723,  1.836685, 16.778881], dtype=float32), array([-9.756529 ,  1.8870208,  9.177772 ], dtype=float32), array([-10.161601 ,   1.8752942,  12.377112 ], dtype=float32), array([-10.170539 ,   1.8457786,  17.977028 ], dtype=float32), array([-10.868057 ,   1.8180857,  14.559721 ], dtype=float32), array([-11.760192 ,   1.9000686,  11.574679 ], dtype=float32), array([-11.669909,   1.82204 ,  15.75848 ], dtype=float32), array([-11.770407 ,   1.8663365,  17.974583 ], dtype=float32), array([-12.484525,   1.783829,  24.957119], dtype=float32), array([-13.265943 ,   1.8552474,  13.356071 ], dtype=float32), array([-13.369633 ,   1.8890027,  17.572144 ], dtype=float32), array([-13.276157 ,   1.8215152,  19.755974 ], dtype=float32), array([-13.286372 ,   1.7877831,  26.155876 ], dtype=float32), array([-13.678679 ,   1.8182217,  21.35534  ], dtype=float32), array([-13.681233 ,   1.8097887,  22.955315 ], dtype=float32), array([-14.566341 ,   1.9149624,  15.570339 ], dtype=float32), array([-15.371381 ,   1.9083753,  18.76907  ], dtype=float32), array([-15.776457 ,   1.8966488,  21.968409 ], dtype=float32), array([-15.6836195,   1.8270531,  24.552235 ], dtype=float32), array([-16.485466 ,   1.8310072,  25.750992 ], dtype=float32), array([-17.773096 ,   1.9328874,  19.965382 ], dtype=float32), array([-17.778204 ,   1.9160213,  23.165335 ], dtype=float32), array([-18.185192,   1.89797 ,  27.564655], dtype=float32), array([-18.974909,   1.941981,  21.16353 ], dtype=float32), array([-18.980017,   1.925115,  24.363482], dtype=float32)]
anno['rotation_y'] ==  [-0.01887922, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, -0.01887922, -0.01887922, -0.01887922, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, -0.01887922, -0.01887922, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, -0.01887922, -0.01887922, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, -0.01887922, -0.01887922, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031, -0.01887922, 1.6205031, -0.01887922, 1.6205031, -0.01887922, -0.01887922, 1.6205031, -0.01887922, -0.01887922, -0.01887922, -0.01887922, 1.6205031, 1.6205031, 1.6205031, -0.01887922, -0.01887922, 1.6205031, 1.6205031, 1.6205031, 1.6205031, 1.6205031]
anno['score'] ==  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
`

**Comment by Rajat-Mehta** [comment]
@MichaelSunEngineer Could you please share how did you solve this issue? Are you able to visualize the detection results ?
