### ISSUE TITLE
Config file for Pedestrian/Cyclist

### ISSUE THREAD

**Issue by s-ryosky** [skyhehe123/SA-SSD#34]
Could you release a config file for pedestrian and cyclist?

**Comment by abhigoku10** [comment]
@skyhehe123 any update on this ??

**Comment by skyhehe123** [comment]
@abhigoku10 still working on :(...

**Comment by abhigoku10** [comment]
@skyhehe123  when is the tentative time i can expect this, i am getting poor results with peds when i modify the config and train

**Comment by skyhehe123** [comment]
@abhigoku10 I don't know, I am working on my boss's project, maybe late in this month ：(......

**Comment by abhigoku10** [comment]
@skyhehe123 wokay thanks for the update !!

**Comment by abhigoku10** [comment]
@stalkermustang have you trained and tested with pedestrain

**Comment by stalkermustang** [comment]
Today i tried to start with Cyclist's, but i'm train on WaymoOpenDataset.

**Comment by abhigoku10** [comment]
@stalkermustang  can you share what hyperparams u have kept and in config also . i will validate with mine

**Comment by stalkermustang** [comment]
What kind of params you mean? i change anchors, and so on.

**Comment by abhigoku10** [comment]
@stalkermustang did u change any params in config , i changed the anchors and on kitti was getting less than 10

**Comment by stalkermustang** [comment]
>i changed the anchors and on kitti was getting less than 10

hm, default anchors in config is for Kitti, or i'm wrong? What's reason for changes?

**Comment by abhigoku10** [comment]
@default anchors in cfg was for cars  , so for peds we need to obtain other vaues

**Comment by bmankirLinker** [comment]
@abhigoku10 Other than the anchor size, you can also consider lowering the `train_cfg` `assigner`'s `iou_th` since the pedestrian/cyclist are smaller their IOUs are more sensitive. 
I haven't tried it at this repo but did similar updates on different LIDAR 3D detection projects for smaller objects.

**Comment by wangzhangfei-hkd** [comment]
@skyhehe123 ，Sorry to disturb you, do you have an update on this question now.

**Comment by skyhehe123** [comment]
@s-ryosky @wangzhangfei-hkd The multiclass training is updated!
