### ISSUE TITLE
 Image_Demo.py or inference_detector

### ISSUE THREAD

**Issue by MichaelSunEngineer** [skyhehe123/SA-SSD#38]
@skyhehe123 Can you add a single point cloud detection code like Image_Demo.py or inference_detector function?? I think it will make the whole project more perfect!

**Comment by stalkermustang** [comment]
You have one
https://github.com/skyhehe123/SA-SSD/blob/master/tools/test.py#L17

**Comment by MichaelSunEngineer** [comment]
＠stalkermustang  test.py is really used to test the test results, but I want to find a code to test my own data, input my own point cloud data, and output the results, instead of using Kitti data set format to encapsulate.

**Comment by stalkermustang** [comment]
For inference on custom data you should cleanup 
https://github.com/skyhehe123/SA-SSD/blob/master/mmdet/datasets/kitti.py#L240
this method (i.e. delete Calib and other), and passing N*4 numpy array of [x,y,z, intens] instead read_lidar call. Is this a problem?

**Comment by MichaelSunEngineer** [comment]
@stalkermustang 
Maybe you have some misunderstandings about my problem. The essence of my problem is how to construct a data dic{} , than put a real-time point cloud data  and other information into the dict, input it into the model, and finally get the result. Because I tried to construct a data dict and input the model directly, but there was an error, maybe because I was not familiar with some structure in the mmdet framework. I do this because the mmdet framework cannot be installed in my test environment.Thanks

**Comment by stalkermustang** [comment]
Can you share example of input that you feed into model? Keys, values types and shapes?

**Comment by MichaelSunEngineer** [comment]
` cfg = mmcv.Config.fromfile('../configs/car_cfg.py')
    cfg.model.pretrained = None
    gpus = 1

    if gpus == 1:
        model = build_detector(
            cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
        #load_checkpoint(model, args.checkpoint)
        model = MMDataParallel(model, device_ids=[0])
        load_params_from_file(model, '../model/checkpoint_epoch_80.pth')

        data_cfg = {'type': 'VoxelGenerator', 'voxel_size': [0.05, 0.05, 0.1], 'point_cloud_range': [0.0, -40.0, -3.0, 70.4, 40.0, 1.0], 'max_num_points': 5, 'max_voxels': 20000}
        generator = obj_from_dict(data_cfg, voxel_generator)

        data ={}
        data['img'] = None
        data['img_meta'] = {'img_shape': (375, 1242, 3), 'sample_idx': 1, 'calib': Calibration('./000020.txt')}

        anchor_generator_cfg = {'type': 'AnchorGeneratorStride', 'sizes': [1.6, 3.9, 1.56], 'anchor_strides': [
            0.4, 0.4, 1.0], 'anchor_offsets': [0.2, -39.8, -1.78], 'rotations': [0, 1.57]}
        anchor_generator = obj_from_dict(anchor_generator_cfg, anchor3d_generator)
        feature_map_size = generator.grid_size[:2] // 8
        feature_map_size = [*feature_map_size, 1][::-1]
        anchors = anchor_generator(feature_map_size).reshape([-1, 7])
        data['anchors'] = DC(to_tensor(anchors.astype(np.float32)))

        points = read_lidar('./000020.bin')
        pc_range = generator.point_cloud_range
        keep = points_op_cpu.points_bound_kernel(points, pc_range[:3], pc_range[3:])
        voxels = points[keep, :]
        voxel_size = generator.voxel_size
        grid_size = generator.grid_size

        coordinates = ((voxels[:, [2, 1, 0]] - np.array(pc_range[[2, 1, 0]], dtype=np.float32)) / np.array(
            voxel_size[::-1], dtype=np.float32)).astype(np.int32)
        num_points = np.ones(len(keep)).astype(np.int32)
        data['voxels'] = DC(to_tensor(voxels.astype(np.float32)))
        print('voxels == ', data['voxels'])
        data['coordinates'] = DC(to_tensor(coordinates))
        data['num_points'] = DC(to_tensor(num_points))
        anchor_area_threshold = 1
        anchors_bv = rbbox2d_to_near_bbox(
            anchors[:, [0, 1, 3, 4, 6]])

        dense_voxel_map = sparse_sum_for_anchors_mask(
            coordinates, tuple(grid_size[::-1][1:]))
        dense_voxel_map = dense_voxel_map.cumsum(0)
        dense_voxel_map = dense_voxel_map.cumsum(1)
        anchors_area = fused_get_anchors_area(
            dense_voxel_map, anchors_bv, voxel_size, pc_range, grid_size)
        anchors_mask = anchors_area > anchor_area_threshold
        data['anchors_mask'] = DC(to_tensor(anchors_mask.astype(np.uint8)))

        data['gt_labels'] = DC(None, cpu_only=True)
        data['gt_bboxes'] = DC(None, cpu_only=True)

        model.eval()
        with torch.no_grad():
            results = model(return_loss=False, **data)
        print(results)

Traceback (most recent call last):
  File "/home/sh/SH/SA-SSD/SA-SSD/tools/3D_Detection1 (复件).py", line 118, in <module>
    main()
  File "/home/sh/SH/SA-SSD/SA-SSD/tools/3D_Detection1 (复件).py", line 113, in main
    results = model(return_loss=False, **data)
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 10, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 48, in scatter_kwargs
    kwargs = scatter(kwargs, target_gpus, dim) if kwargs else []
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 40, in scatter
    return scatter_map(inputs)
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 30, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 25, in scatter_map
    return list(zip(*map(scatter_map, obj)))
TypeError: zip argument #2 must support iteration

`

**Comment by stalkermustang** [comment]
The problem in types of object you store in dict. I.e. check image meta and scalars in code:
https://github.com/skyhehe123/SA-SSD/blob/master/mmdet/datasets/kitti.py#L266
(wrapped in DC, DataContainer) and 
```data['img_meta'] = {'img_shape': (375, 1242, 3), 'sample_idx': 1, 'calib': Calibration('./000020.txt')}```
where dict passed.

All data should be wrapped in DC, and non-necessary variables can be like  
```DC(None, cpu_only=True)```

non-CPU variables SHOULD be torch tensors wrapped in DC

**Comment by abhigoku10** [comment]
@stalkermustang can this changes made will help to run on cpu ??

**Comment by stalkermustang** [comment]
Of course no :)

**Comment by MichaelSunEngineer** [comment]
@stalkermustang I set the data['img'] = DC(None, cpu_only=True)
    data['img_meta'] = DC({'img_shape': (375, 1242, 3), 'sample_idx': 1, 'calib': Calibration('./000020.txt')}, cpu_only=True), but still error.this my code name test1.py in tools/  and run python test1.py. Can you help me make some changes when you have time? 
import torch
import mmcv
import sys
sys.path.append('/home/sh/SH/SA-SSD/SA-SSD')
from mmcv.parallel import DataContainer as DC
from mmcv.parallel import scatter, collate, MMDataParallel
from mmdet.datasets.utils import to_tensor
from mmdet.datasets.kitti_utils import read_lidar, Calibration
from mmdet.core.point_cloud import voxel_generator
from mmdet.core.anchor import anchor3d_generator
from mmdet.core.bbox3d.geometry import rbbox2d_to_near_bbox, sparse_sum_for_anchors_mask, fused_get_anchors_area
from mmcv.runner import obj_from_dict
from mmdet.models import build_detector, detectors
from mmdet.ops.points_op import points_op_cpu
import numpy as np
import torch.utils.data
from tools.train_utils import load_params_from_file


def main():
    cfg = mmcv.Config.fromfile('../configs/car_cfg.py')
    cfg.model.pretrained = None
    model = build_detector(
        cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
    #load_checkpoint(model, args.checkpoint)
    model = MMDataParallel(model, device_ids=[0])
    load_params_from_file(model, '../model/checkpoint_epoch_80.pth')

    data_cfg = {'type': 'VoxelGenerator', 'voxel_size': [0.05, 0.05, 0.1], 'point_cloud_range': [0.0, -40.0, -3.0, 70.4, 40.0, 1.0], 'max_num_points': 5, 'max_voxels': 20000}
    generator = obj_from_dict(data_cfg, voxel_generator)

    data ={}
    data['img'] = DC(None, cpu_only=True)
    data['img_meta'] = DC({'img_shape': (375, 1242, 3), 'sample_idx': 1, 'calib': Calibration('./000020.txt')}, cpu_only=True)

    anchor_generator_cfg = {'type': 'AnchorGeneratorStride', 'sizes': [1.6, 3.9, 1.56], 'anchor_strides': [0.4, 0.4, 1.0], 'anchor_offsets': [0.2, -39.8, -1.78], 'rotations': [0, 1.57]}
    anchor_generator = obj_from_dict(anchor_generator_cfg, anchor3d_generator)
    feature_map_size = generator.grid_size[:2] // 8
    feature_map_size = [*feature_map_size, 1][::-1]
    anchors = anchor_generator(feature_map_size).reshape([-1, 7])
    data['anchors'] = DC(to_tensor(anchors.astype(np.float32)))

    points = read_lidar('./000020.bin')
    pc_range = generator.point_cloud_range
    keep = points_op_cpu.points_bound_kernel(points, pc_range[:3], pc_range[3:])
    voxels = points[keep, :]
    voxel_size = generator.voxel_size
    grid_size = generator.grid_size

    coordinates = ((voxels[:, [2, 1, 0]] - np.array(pc_range[[2, 1, 0]], dtype=np.float32)) / np.array(
        voxel_size[::-1], dtype=np.float32)).astype(np.int32)
    num_points = np.ones(len(keep)).astype(np.int32)
    data['voxels'] = DC(to_tensor(voxels.astype(np.float32)))
    print('voxels == ', data['voxels'])
    data['coordinates'] = DC(to_tensor(coordinates))
    data['num_points'] = DC(to_tensor(num_points))
    anchor_area_threshold = 1
    anchors_bv = rbbox2d_to_near_bbox(
        anchors[:, [0, 1, 3, 4, 6]])

    dense_voxel_map = sparse_sum_for_anchors_mask(
        coordinates, tuple(grid_size[::-1][1:]))
    dense_voxel_map = dense_voxel_map.cumsum(0)
    dense_voxel_map = dense_voxel_map.cumsum(1)
    anchors_area = fused_get_anchors_area(
        dense_voxel_map, anchors_bv, voxel_size, pc_range, grid_size)
    anchors_mask = anchors_area > anchor_area_threshold
    data['anchors_mask'] = DC(to_tensor(anchors_mask.astype(np.uint8)))

    data['gt_labels'] = DC(None, cpu_only=True)
    data['gt_bboxes'] = DC(None, cpu_only=True)

    model.eval()
    with torch.no_grad():
        results = model(return_loss=False, **data)
    print(results)


if __name__ == '__main__':
    main()

**Comment by stalkermustang** [comment]
The problem is in 
https://github.com/skyhehe123/SA-SSD/blob/master/mmdet/models/detectors/single_stage.py#L128
that returns is'nt standart format for DataParallel.
Have no idea why with single gpu scatter_gather was called, but you can use model.module() forward after load weights instead model() call.
```results = model.module(return_loss=False, **data)```

**Comment by MichaelSunEngineer** [comment]
@stalkermustang I try the results = model.module(return_loss=False, **data), still error.Are you run success with this change in my code?

**Comment by stalkermustang** [comment]
What error you get, exact same?
```File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 30, in scatter_map
out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
File "/home/sh/anaconda3/envs/sa-ssd/lib/python3.6/site-packages/mmcv/parallel/scatter_gather.py", line 25, in scatter_map
return list(zip(*map(scatter_map, obj)))
TypeError: zip argument #2 must support iteration```

as previous time?

**Comment by stalkermustang** [comment]
can you pickle.dump ```data``` object and share?

**Comment by MichaelSunEngineer** [comment]
@stalkermustang   
File "/home/sh/SH/SA-SSD/SA-SSD/mmdet/models/detectors/single_stage.py", line 84, in merge_second_batch
    ret[key] = torch.stack(elems, dim=0)
TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not set

**Comment by MichaelSunEngineer** [comment]
@stalkermustang
[data_dict.txt](https://github.com/skyhehe123/SA-SSD/files/4654524/data_dict.txt)

**Comment by stalkermustang** [comment]
ah, ye. Can you change all values in data dict to list of item? Like 
```
for k, v in data:
    data[k] = [v]
```


and try to run?

**Comment by abhigoku10** [comment]
@MichaelSunEngineer  where you able to get the single inference code running

**Comment by Royaler** [comment]
@stalkermustang do you know how to run the code only on cpu

**Comment by stalkermustang** [comment]
think there's no option for cpu run cause some ops writen as cuda ops (not cpu)
