### ISSUE TITLE
Pointwise feature interpolation implementation

### ISSUE THREAD

**Issue by bmankirLinker** [skyhehe123/SA-SSD#39]
In the paper, the mentioned interpolation algorithm (distance-based) and the implemented (kNN) is different, where the implemented one is the same as it is in the`Pointnet++`. Is it worth trying different mechanisms or do the authors already concluded kNN works better in terms of performance in the KITTI dataset?

**Comment by skyhehe123** [comment]
@bmankirLinker You are right, the original ball query is time-consuming in training while using 3 nearest neighbors to propagate the features can achieve same funtionality and more efficient.
