### ISSUE TITLE
About input data representation

### ISSUE THREAD

**Issue by djiajunustc** [skyhehe123/SA-SSD#40]
Hi,
In your paper, you describe that:
If multiple points share the same index, we overwrite the entry with the latest point. We find that this pre-processing method is efficient and adequate to achieve reasonable performance with a finer quantization step d = [0:05m; 0:05m; 0:1m].

But I find that in your implementation (mmdet/ops/points_op/opints_op.py), you take the same voxelization strategy as that in SECOND. 

Maybe the method in your description and the implementation make the similar effect on the performance. 
Please let me know whether my understanding is correct.

Thanks a lot !

**Comment by 23sena** [comment]
@djiajunustc the original voxelization method is converted into comment, the alternative one can bring save the runtime in preprocessing
https://github.com/skyhehe123/SA-SSD/blob/9bb2ef4aecc7206ea935977d45781267b8a15001/mmdet/datasets/kitti.py#L185-L198
