### ISSUE TITLE
cannot import name 'CocoDistEvalRecallHook' from 'mmdet.core'

### ISSUE THREAD

**Issue by oby-yang** [skyhehe123/SA-SSD#42]
error: cannot import name 'CocoDistEvalRecallHook' from 'mmdet.core'
how to solve it? @skyhehe123

**Comment by ZaiwangLi** [comment]
hi, you need "export PYTHONPATH="path/to/sassd"

**Comment by xuntan97** [comment]
> error: cannot import name 'CocoDistEvalRecallHook' from 'mmdet.core'
> how to solve it? @skyhehe123

hi, i have the same mistake. Can you tell me how to solve it? Thank you!
