### ISSUE TITLE
The detector can run at 25 FPS with a single 1080ti？

### ISSUE THREAD

**Issue by whj8810** [skyhehe123/SA-SSD#57]
hello,author,do you run it with a single 1080ti ? I can not run detector at 25 fps  with a single 1080TI gpu.I don't know why I can almost run at 6 fps when i test it.

**Comment by skyhehe123** [comment]
In my case, the detector can run at 25FPS with 2080Ti

**Comment by kaushik333** [comment]
Can you please share how you are visualizing results? This codebase doesnt seem to provide any. Thanks in advance.

**Comment by lihua213** [comment]
> In my case, the detector can run at 25FPS with 2080Ti

Hello, my dear friend, I get a speed at 15FPS on a TITAN RTX GPU. is there a code to test the speed? Thanks so much.

**Comment by wangzhangfei-hkd** [comment]
Hello, what is the speed of multi classification detection on 2080ti? I am looking forward to your reply. Thank you
