### ISSUE TITLE
would you add all_cfg.py for training? 

### ISSUE THREAD

**Issue by wyjforwjy** [skyhehe123/SA-SSD#7]
Is there any result for all classes ?And did you try trainning for all classes?

**Comment by wyjforwjy** [comment]
Hope for your reply. And thanks for sharing your work!

**Comment by skyhehe123** [comment]
@wyjforwjy Yes, I am working on training for all classes.

**Comment by abhigoku10** [comment]
@skyhehe123  when can we expect the training for all classes output or can you let us know / share for pedestrain/people class the config
