### ISSUE TITLE
how to generate .bin for "velodyne_reduced"?

### ISSUE THREAD

**Issue by linbaiwpi** [skyhehe123/SA-SSD#71]
Hi when running "create_data.py", I encountered an error as below.
**FileNotFoundError: [Errno 2] No such file or directory: '/SA-SSD/data/training/velodyne_reduced/000000.bin'**

May I know how can I generate the .bin files for folder "velodyne_reduced"?

**Comment by praj441** [comment]
You need to create the folder velodyne_reduced manually before you run the create_data.py file.

**Comment by linbaiwpi** [comment]
> You need to create the folder velodyne_reduced manually before you run the create_data.py file.

Thank you for the reply. But how can I generate it manually?

**Comment by praj441** [comment]
Its really simple, Go to at /SA-SSD/data/training/ and just use mkdir command (to create a new directory)

**Comment by linbaiwpi** [comment]
> Its really simple, Go to at /SA-SSD/data/training/ and just use mkdir command (to create a new directory)

oh, just create a empty directory. thanks!
