### ISSUE TITLE
error on RTX3090

### ISSUE THREAD

**Issue by vehxianfish** [skyhehe123/SA-SSD#92]
Hi,thanks for your greak job .I use 3090 to run the program.But errors always occurs:
In code:
```
    xg, yg, wg, lg, rg = torch.split(box, 1, dim=-1)

    xg = xg.unsqueeze_(-1).expand(N, *window_size)
    yg = yg.unsqueeze_(-1).expand(N, *window_size)
    rg = rg.unsqueeze_(-1).expand(N, *window_size)
```
the errors :
```
  File "/media/m3090/xu/detection/lidar/SA-SSD/mmdet/models/single_stage_heads/ssd_rotate_head.py", line 385, in gen_sample_grid
    yg = yg.unsqueeze_(-1).expand(N, *window_size)
RuntimeError: diff_view_meta->output_nr_ == 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/variable.cpp":363, please report a bug to PyTorch.
```
and only `yg,rg` have this error,`xg,wg,lg` don not have errors.it confused me a lot.
My lib version:
```
pytorch=1.7.1+cu11
spconv=1.0
RTX3090
```
anyone meet this question?Thank you!

**Comment by vehxianfish** [comment]
I have solved it,Thank you!

**Comment by Jackman0316** [comment]
I got the same error. Do you remember what's the reason for this? Thank you very much!

**Comment by Jackman0316** [comment]
Changing .unsqueeze_(-1) to .unsqueeze(-1) solved this, Only happens in yg and rg, so weird.

**Comment by vehxianfish** [comment]
> Changing .unsqueeze_(-1) to .unsqueeze(-1) solved this, Only happens in yg and rg, so weird.

Sorry,so later to reply you.I only remember the reastion.because pytorch version has changed a lot.you should use alternative operations.
